name: rush build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      # - run: node common/scripts/install-run-rush.js change -v
      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js rebuild --verbose
      - run: node common/scripts/install-run-rush.js test

      # build interoperating.app/menu apps to be released
      - run: npm -w interoperating.app/menu run make
