name: rush build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      # - run: node common/scripts/install-run-rush.js change -v
      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js rebuild --verbose
      - uses: actions/upload-artifact@v3
        with:
          name: repo.root
          path: .
  test:
    runs-on: ubuntu-latest
    needs:
    - install
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: repo.root
        path: .
    - run: node common/scripts/install-run-rush.js run test
  build-electron:
    runs-on: ubuntu-latest
    needs:
    - install
    steps:
    - run: npm -w interoperating.app/menu run make
